mapa = [
    "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    "ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    "nnnnnngggggccccccccccccccccccccccccccccgggggnnnnnnnnnnnnnnn",
    "nnnnnngggggccccccccccccccccccccccccccccgggggnnnnnnnnnnnnnnn",
    "nnnnnngggggccccccccccccccccccccccccccccgggggnnnnnnnnnnnnnnn",
    "nnnnnngggggccccccccccccccccccccccccccccgggggnnnnnnnnnnnnnnn",
    "nnnnnnnnggggggccccccccccccccccccccccggggggnnnnnnnnnnnnnnnnn",
    "nnnnnnnnggggggccccccccccccccccccccccggggggnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnggggggccccccccccccccggggggnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnggggggccccccccccccccggggggnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnggggggccccccggggggnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnggggggccccccggggggnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnnnnncccccccccccccnnnnnnnnnnnnnnnnnnnnnnnnnnn",
]
obj = [
    "                                                           ",
    "                                                           ",
    "                                                   t  t    ",
    "                                                  a    a   ",
    "    t                                    a                 ",
    "                                             t a   t  a    ",
    "    t a                                                    ",
    "                                          a   t    a       ",
    "  t                                                   a    ",
    "      a t                                     t    t       ",
    "                                                           ",
    "    a  t                                   t     a    a    ",
    "  a    t   a       hhh      hhh     a   t  a         a t   ",
    "       a   t   t   a h      h a     t   a  t   a   a   t   ",
    "   t      t        t h      h a  t   t   t    a      t  t  ",
    "        t    a  t  a          t    t   t  a  t    t     a  ",
    "    a  t    t      a          a      a    a    t     a     ",
    "      a   t   t    t          a   t   t      t     a       ",
    "    a              a          t    a     t       a    t    ",
    "      a   t   t    t          t     a  t   a     t  t      ",
    "   t  a   a t      a          t t  a        a  t    a  t   ",
    " a  a t     a      t          a     t  t    a    t a  t    ",
    "     a     t    a  t          a  t  a    t      t   a      ",
    "   a  t t          t          a a   t   a a  t  t   a  t   ",
    "   t         a     a          t     a t  t  t   t   a      ",
    "     t  a          a          a  t t     t a  t      t     ",
    "   t    t   t  a   a          t      a  t      t  a    t   ",
    "  a   a   a        t          at  a      a   t  t   t      ",
    "   t         a     a          a       t      a   aa t    t t",
    "   t   t     t     a          a      t   a   a       a   t ",
    " t a               t          t t      a        t     tt   ",
    "       a  t   t    t          a     a    t    t      t t   ",
    "  a  t   t   a     a          a a                a         ",
    "  t     a    a     a          t    a  a    t a  a  a  t    ",
    "                   a          t  a    t     a   t t     a  ",
]